name: Check and Restart Answers TG Bot
 
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Bot Health
        id: status
        run: |
          RESPONSE=$(curl -s "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/getMe")
          if [[ "$RESPONSE" == *"\"ok\":true"* ]]; then
            echo "alive=true" >> $GITHUB_OUTPUT
          else
            echo "alive=false" >> $GITHUB_OUTPUT
          fi

      - name: Restart and Notify
        # if: steps.status.outputs.alive == 'false'
        run: |
          ALIVE="${{ steps.status.outputs.alive }}"
          # 1. Перезапуск на PythonAnywhere
          RESTART_RES=$(curl -s -X POST \
            "https://www.pythonanywhere.com/api/v0/user/${{ secrets.PA_USERNAME }}/webapps/${{ secrets.PA_DOMAIN }}/reload/" \
            -H "Authorization: Token ${{ secrets.PA_API_TOKEN }}")
          
          # 2. Уведомление в Telegram
          MSG="Сервер PythonAnywhere перезапущен. %0AБот работал при проверке: $ALIVE %0AОтвет после перезапуска: $RESTART_RES"
          
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=$MSG&parse_mode=Markdown"
