on:
  schedule:
    - cron: '0 13 * * *' 

jobs:
  call-main:
    uses: ./.github/workflows/download_report_xml.yml
    with:
      period: '02/2026'
      nullsum: true
      ownstructure: false
      hidezombnull: false
