name: Group Email Dispatch2

on:
  workflow_dispatch: # Позволяет запускать рассылку вручную

jobs:
  send-mail:
    runs-on: ubuntu-latest
    steps:
      - name: Send group email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Тема вашей рассылки"
          # Список получателей через запятую
          to: alex.mokrushin@gmail.com
          from: "Ваше Имя <${{ secrets.MAIL_USERNAME }}>"
          body: "Привет! Это текст группового письма, отправленного через GitHub Actions."
          # Для скрытой рассылки используйте bcc вместо to
          bcc: alex_mokrushin@mail.ru 
          secure: true
