name: Format XML with Prettier

on:
  push:
    paths:
      - '**/*.xml' # Запускать, только если изменились XML
  pull_request:
    branches: [ main ]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Важно для корректной работы git-экшенов

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Prettier and XML Plugin
        run: npm install prettier @prettier/plugin-xml

      - name: Run Prettier
        # --write перезапишет файлы, --check просто проверит
        run: npx prettier --write "**/*.xml"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: format XML files with prettier"
          file_pattern: '**/*.xml'
