name: Send E-mails to new consultants 

on:
  push:
    paths:
      - 'mailing/ConsultantTreeMLM*.xml'
      - 'mailing/ReportMLM2MC.xml'
  workflow_dispatch:

jobs:
  build-contacts-list:
    runs-on: ubuntu-latest
    outputs:
      # Прокидываем output шага на уровень всей джобы
      should_send: ${{ steps.detector.outputs.need_send_mail }}
      file_name: "contacts_new_with_dates.json" # Передаем имя файла
    env:
      REPORT_TYPE: 'none' 
      REPORT_NAME: 'none' # Инициализация, чтобы избежать ошибки доступа
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Обязательно: выкачиваем историю, чтобы сравнить коммиты

      - name: Detect File
        id: detector
        run: |
          # Получаем список измененных файлов в текущем пуше
          CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})

          echo "Обнаружены изменения в файлах:"
          echo "$CHANGED_FILES"

          # Проверяем наличие конкретных файлов
          if echo "$CHANGED_FILES" | grep -q "mailing/ReportMLM2MC.xml"; then
            echo "REPORT_TYPE=ReportMLM2MC" >> $GITHUB_ENV
            echo "need_send_mail=false" >> $GITHUB_OUTPUT
          elif echo "$CHANGED_FILES" | grep -q "mailing/ConsultantTreeMLM.*\.xml"; then
            echo "REPORT_TYPE=ConsultantTreeMLM" >> $GITHUB_ENV
            echo "need_send_mail=true" >> $GITHUB_OUTPUT
          fi

          # Ищем файл в списке измененных по маске
          # Используем -o для вывода только совпадения и basename для очистки пути
          MATCHED_FILE=$(echo "$CHANGED_FILES" | grep -oE "mailing/(ReportMLM2MC|ConsultantTreeMLM)[^ ]*\.xml" | head -n 1)

          if [ -n "$MATCHED_FILE" ]; then
            # Убираем путь "mailing/" и расширение ".xml"
            FILENAME=$(basename "$MATCHED_FILE" .xml)  
            echo "REPORT_NAME=$FILENAME" >> $GITHUB_ENV
            echo "found=true" >> $GITHUB_OUTPUT
            echo "Найдено: $FILENAME"
          else
            echo "found=false" >> $GITHUB_OUTPUT
            echo "Файлы не найдены"
          fi
      - name: Install xsltproc
        run: |
          sudo apt-get update
          sudo apt-get install -y xsltproc

      - name: Use result
        if: steps.detector.outputs.found == 'true'
        run: |
          echo "Работаем с отчетом: ${{ env.REPORT_NAME }}"
          
      - name: Transform XML to JSON
        run: |
          # Получаем дату в нужном формате
          YESTERDAY=$(date -d 'yesterday' +'%Y-%m-%dT00:00:00')
          # Выводим в консоль для проверки
          echo "Value of YESTERDAY: $YESTERDAY"
          # Запускаем трансформацию с параметрами
          xsltproc --stringparam fromDate "$YESTERDAY" \
                   --stringparam toDate "$YESTERDAY" \
                   mailing/contacts_new_${REPORT_TYPE}.xsl mailing/${REPORT_NAME}.xml > contacts_new_with_dates.json
          # Считаем элементы и выводим в консоль
          COUNT=$(jq '. | length' contacts_new_with_dates.json)
          echo "Количество элементов в файле: $COUNT"
          # Вывод результата в лог для проверки
          cat contacts_new_with_dates.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mail-contacts
          path: contacts_new_with_dates.json

  # 2. Вторая джоба: запуск рассылки по условию
  send-emails:
    needs: build-contacts-list
    # Условие: запускать только если в первой джобе вернули 'true'
    if: needs.build-contacts-list.outputs.should_send == 'true'
    uses: ./.github/workflows/email_blast_with_delay.yml
    with:
      # Используем имя файла, которое передали из первой джобы
      contacts_name: ${{ needs.build-contacts-list.outputs.file_name }}
      template_name: 'mailing/new.txt'
      delay_seconds: '3'
    secrets: inherit

