name: Send E-mails to new consultants 

on:
  push:
    paths:
      - 'mailing/ConsultantTreeMLM.xml'
  workflow_dispatch:

jobs:
  build-contacts-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install xsltproc
        run: |
          sudo apt-get update
          sudo apt-get install -y xsltproc
          
      - name: Transform XML to JSON
        run: |
          # Получаем дату в нужном формате
          YESTERDAY=$(date -d 'yesterday' +'%Y-%m-%dT00:00:00')
          # Выводим в консоль для проверки
          echo "Value of YESTERDAY: $YESTERDAY"
          # Запускаем трансформацию с параметрами
          xsltproc --stringparam fromDate "$YESTERDAY" \
                   --stringparam toDate "$YESTERDAY" \
                   mailing/contacts_new_with_dates.xsl mailing/ConsultantTreeMLM.xml > contacts_new_with_dates.json
          # Вывод результата в лог для проверки
          cat contacts_new_with_dates.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: new-contacts
          path: contacts_new_with_dates.json
