name: Send E-mails to 6 or 18 periods inactive consultants

on:
  workflow_dispatch:
    inputs:
        report:
          description: 'Использовать отчет'
          required: true
          default: 'ReportMLM2MC.xml'
          type: choice
          options:
            - ReportMLM2MC
            - ConsultantTreeMLM
        idle_periods:
          description: 'Периоды неактивности'
          required: true
          default: '18'
          type: choice
          options:
            - 6
            - 18

jobs:
  build-contacts-list:
    runs-on: ubuntu-latest
    outputs:
      # Прокидываем output шага на уровень всей джобы
      should_send: ${{ steps.detector.outputs.need_send_mail }}
      file_name: "contacts_remove.json" # Передаем имя файла
    env:
      REPORT_TYPE: 'none' 
      REPORT_NAME: 'none' # Инициализация, чтобы избежать ошибки доступа
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Обязательно: выкачиваем историю, чтобы сравнить коммиты

      - name: Detect File
        id: detector
        run: |
            echo "REPORT_TYPE=${{inputs.report}}" >> $GITHUB_ENV
            echo "need_send_mail=true" >> $GITHUB_OUTPUT
            echo "REPORT_NAME='mailing/${{inputs.report}}'" >> $GITHUB_ENV
            echo "found=true" >> $GITHUB_OUTPUT
            echo "Используем: $FILENAME"
      - name: Install xsltproc
        run: |
          sudo apt-get update
          sudo apt-get install -y xsltproc

      - name: Use result
        if: steps.detector.outputs.found == 'true'
        run: |
          echo "Работаем с отчетом: ${{ env.REPORT_NAME }}"
          
      - name: Transform XML to JSON
        run: |
          # Запускаем трансформацию
          xsltproc contacts_remove{{inputs.idle_periods}}_${REPORT_TYPE}.xsl mailing/${REPORT_NAME}.xml > contacts_remove.json
          # Считаем элементы и выводим в консоль
          COUNT=$(jq '. | length' contacts_remove.json)
          echo "Количество элементов в файле: $COUNT"
          # Вывод результата в лог для проверки
          cat contacts_remove.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mail-contacts
          path: contacts_remove.json

  # 2. Вторая джоба: запуск рассылки по условию
  send-emails:
    needs: build-contacts-list
    # Условие: запускать только если в первой джобе вернули 'true'
    if: needs.build-contacts-list.outputs.should_send == 'true'
    uses: ./.github/workflows/email_blast_with_delay.yml
    with:
      # Используем имя файла, которое передали из первой джобы
      contacts_name: ${{ needs.build-contacts-list.outputs.file_name }}
      template_name: 'mailing/remove{{inputs.idle_periods}}.txt'
      delay_seconds: '3'
    secrets: inherit
